export const PREDEFINED_ACADEMIES = [
  { value: 'Real Samuray', label: 'Real Samuray' },
  { value: 'CCM Alfredo Chaves', label: 'CCM Alfredo Chaves' },
  { value: 'Djalma Johnsson', label: 'Djalma Johnsson' },
  { value: 'Azevedo', label: 'Azevedo' },
  { value: 'JC (José Calixto)', label: 'JC (José Calixto)' },
  { value: 'CT Brasa', label: 'CT Brasa' },
  { value: 'Base TKD', label: 'Base TKD' },
  { value: 'Dojo Hamdar', label: 'Dojo Hamdar' },
  { value: 'Leia Helena TKD', label: 'Leia Helena TKD' },
  { value: 'King of Fight', label: 'King of Fight' },
  { value: 'Liga Pegasus', label: 'Liga Pegasus' },
  { value: 'Liga Shekinah', label: 'Liga Shekinah' },
  { value: 'Tae Kombat', label: 'Tae Kombat' },
  { value: 'Guerra TKD', label: 'Guerra TKD' },
  { value: 'Sadrak Lutas (pro. Sadrak)', label: 'Sadrak Lutas (pro. Sadrak)' },
  { value: 'Escola de Taekwondo (prof Roy)', label: 'Escola de Taekwondo (prof Roy)' },
  { value: 'TKD Kajuru', label: 'TKD Kajuru' },
  { value: 'Dinamite', label: 'Dinamite' },
  { value: 'Outra', label: 'Outra (Digitar manualmente)' }
];

export const BELT_OPTIONS = [
  { value: '10º Gub - Branca', label: '10º Gub - Branca' },
  { value: '9º Gub - Cinza', label: '9º Gub - Cinza' },
  { value: '8º Gub - Amarela', label: '8º Gub - Amarela' },
  { value: '7º Gub - Laranja', label: '7º Gub - Laranja' },
  { value: '6º Gub - Verde Claro', label: '6º Gub - Verde Claro' },
  { value: '5º Gub - Verde Escuro', label: '5º Gub - Verde Escuro' },
  { value: '4º Gub - Azul Claro', label: '4º Gub - Azul Claro' },
  { value: '3º Gub - Azul Escuro', label: '3º Gub - Azul Escuro' },
  { value: '2º Gub - Vermelha', label: '2º Gub - Vermelha' },
  { value: '1º Gub - Vermelha Escura', label: '1º Gub - Vermelha Escura' },
  { value: '1º Dan - Preta', label: '1º Dan - Preta' },
  { value: '2º Dan - Preta', label: '2º Dan - Preta' },
  { value: '3º Dan - Preta', label: '3º Dan - Preta' },
  { value: '4º Dan - Preta', label: '4º Dan - Preta' },
  { value: '5º Dan - Preta', label: '5º Dan - Preta' },
  { value: '6º Dan - Preta', label: '6º Dan - Preta' },
  { value: '7º Dan - Preta', label: '7º Dan - Preta' },
  { value: '8º Dan - Preta', label: '8º Dan - Preta' },
  { value: '9º Dan - Preta', label: '9º Dan - Preta' },
  { value: '10º Dan - Preta', label: '10º Dan - Preta' },
];
